### PR TITLE
Adding support for inline docs in enums

### PR DESCRIPTION
**Pull request by dr-orlovsky**

### CODE REVIEW

**Comment by elichai** [comment]
Thanks.
Published.

**Comment by elichai** [comment]
It's weird that my proc-macro get's the `doc` as an attribute even though I don't specify it as a supported attribute by my crate.
I wonder now if this can also interact badly with other attribute macros

**Comment by dr-orlovsky** [comment]
> I wonder now if this can also interact badly with other attribute macros

Maybe follow a general principle of keeping unknown attributes and not failing on them?

**Comment by elichai** [comment]
@dr-orlovsky if it actually passes all the attributes to me then I'll do that, but I prefer to try and check first

**Pull request merged**
